### ISSUE TITLE
Unknown trust provider

### ISSUE THREAD

**Issue by GCRaistlin** [KOLANICH/CleanUnwantedUpdates#2]
I know that isn't really a CleanUnwantedUpdates issue, but still. I get the following error:
`C:\Programs\CleanUnwantedUpdates-fixing-WinHttpRequest\CleanUnwantedUpdates.wsf(
152, 3) (null): Unknown trust provider.`
CheckSUR and sfc /scannow detect no issues on the system.

**Comment by KOLANICH** [comment]
Sorry, I have no idea. Have never encountered that. First of all try to find the file where it throws: either use some WSH debugger, or just add an empty line into each js file in ```src``` folder of the tool one-by-one, restart the tool and look for changes in the first number in the error message.

**Comment by GCRaistlin** [comment]
It's in libMSUpdater.js.

**Comment by KOLANICH** [comment]
try in an elevated cmd/powershell
```
net start appidsvc
net start cryptsvc
```

**Comment by GCRaistlin** [comment]
This didn't help.

**Comment by KOLANICH** [comment]
Hmm. Have you tried to [reset windows update](https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc)? 

Also try nuking windows update settings in registry ( ```HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate``` and ``` HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate``` ).

**Comment by GCRaistlin** [comment]
Solved. It was because of CryptoPro. The official patch (available on https://www.cryptopro.ru/downloads) fixes the issue, as well as error 800b0001 in Windows Update.
Thanks for the help!

**Comment by KOLANICH** [comment]
>Thanks for the help!

In fact I haven't managed to help you. So thank yourself ;)

**Comment by GCRaistlin** [comment]
Actually you did by directing me in the right way.
