### ISSUE TITLE
Uninstall failure?

### ISSUE THREAD

**Issue by GCRaistlin** [KOLANICH/CleanUnwantedUpdates#3]
Every time I'm getting the same result:
`Getting list of updates...
230 updates found. Filtering ....
Updating config...
Detection results:
Following updates will be uninstalled:
        {62c68477-0f45-46aa-8af8-d0c189d6dd8e} KB971033 | Update for Windows 7 for x64-based Systems (KB971033) [ http://go.microsoft.com/fwlink/?LinkId=161784
http://www.microsoft.com/genuine ]

Uninstalling...
Uninstallation failed:`

**Comment by KOLANICH** [comment]
1 What is the error message?
2 Have you tried to uninstall that update manually?
3 It seems I cannot help you to deal with Windows Update troubles better than Google. The tool only uses its api to get the information about updates and to trigger uninstallation and hiding of unneeded ones. Use Google.

**Comment by GCRaistlin** [comment]
There's no error message as you can see. It just remains installed.
And thanks again for the idea - manual uninstalling was successful. I noticed that Publisher field was empty for this update on Installed Updates page while all other updates have "Microsoft Corporation" there. Might it be the reason why it couldn't be uninstalled by your tool?

**Comment by KOLANICH** [comment]
Don't know. I guess the API is for all the updates, not only for the MS ones. And I also guess that that update is the MS one.
